name: Create Daily Demo Project

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 1 * * *'

jobs:
  test:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: (1) Clone Code
        uses: actions/checkout@v3
      
      - name: (2) Install NightVision
        run: |
            wget -c https://downloads.nightvision.net/binaries/latest/nightvision_latest_linux_amd64.tar.gz -O - | tar -xz; sudo mv nightvision /usr/local/bin/
                    python -m pip install semgrep --user

      - name: (3) Create Project
        run: |
          sh simple-deploy.sh "demo-$(date +"%s")"

      - name: (4) Create everything and Scan the API
        run: |
          sh simple-deploy.sh "demo-$(date +"%s")"
